// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytzexfjlrstqvsbcnvdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0emV4ZmpscnN0cXZzYmNudmRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxMzk4NjEsImV4cCI6MjA4OTcxNTg2MX0.rkvP5UthsmtUYvB5Ca7zu6DUeku_6IJ4NtcbJMpjp5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});